site_name: My Docs
nav:
  - Домашняя: index.md
  - Первая лабораторная: lab1.md
  - Вторая лабораторная: lab2.md
  - Контакты: contact.md
theme:
  name: mkdocs
  locale: ru
  color_mode: dark
  user_color_mode_toggle: true
  custom_dir: custom/
