name: Build and Deploy of Static Site

on:
  push:

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: MkDocs Setup
        run: pip install mkdocs

      - name: Build
        run: mkdocs build

      - name: Install SSH key

        run: 
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.PRIVATE_SSH_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.KNOW_HOSTS }}" > ~/.ssh/known_hosts

      # - name: Deploy
      #   # run rsync --archive --stats site/ ${{ secrets.REMOTE_DEST }}

