name: Deploy MKDocs

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material

      - name: Install PostCSS and HTML Validator
        run: |
          npm install -g postcss postcss-cli autoprefixer cssnano html-validator-cli

      - name: Build the site
        run: |
          mkdocs build

      - name: Validate and Minify CSS
        run: |
          postcss site/css/base.css --use autoprefixer cssnano -o site/css/base.min.css

      - name: Validate HTML
        run: |
          html-validator --file=site/index.html --verbose

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./site
          force_orphan: true
